# Generated by Django 2.1.1 on 2018-10-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('cmmnt', models.CharField(max_length=50)),
            ],
        ),
    ]
